### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abmAsadullah**
* Mutual friendship

### CODE REVIEW

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Guys

THIS IS VERY IMPRESSIVE WORK. YOU HAVE DONE A GOOD JOB :+1:
However, there are some changes that you need to make in order to get your project approved

- [x] I got this error when I accepted a friend request
err


- [x] Your pr title and description is not descriptive enough

- [x] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)


 >Users who need to confirm friendship
 
      has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", 
      foreign_key: "user_id"
      has_many :pending_friends, through: :pending_friendships, source: :friend


- [x] With this line of code, you can find user friends only by user_id in the friendships table

       has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
       has_many :friends, through: :confirmed_friendships

- [x] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

        has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
        has_many :friend_requests, through: :inverted_friendships



Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑🛑**

Hello @abmAsadullah 
Great job making the previous requested changes.
However let's make few changes and get it approved.

[REQUIRED]: Like the previous TSE pointed out, when I accept a friend request I get this error below. Kindly fix it.
error

Kindly make the required changes and ask for another review👍👍
Happy coding💻💻

**Comment by abmAsadullah** [comment]
**It's working in my computer.**

image

image

* I cloned this ripo another directory and checked many times. It's working all times in my computer. May be I'm using Windows-10 and you are using another operating system.

**Review by whiz25 — APPROVED** [review]
## Approved ✅ ✅ ✅ 
Nice work making the requested changes. A user can now accept a friend request from other users.
Merge and proceed to the next project.


### Martin Afani
#### Slack: whiz25

**Pull request merged**
