### PR TITLE
Friendship model

### PR DESCRIPTION
**Pull request by abmAsadullah**
* Add friendship model

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Asad Asadullah** 
Good job with your first submission for this project :muscle:  :muscle: 
Some improvements are required before you can go ahead:

- [ ] Add rspec tests to your project.
- [ ] After logging, the root page of the project should only show comments from the current user and its friends.
- [ ] Current user should be able to make friendship requests.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:wrench::hammer::full_moon:
**Hi Asad!
Great job so far:clap::clap:. However, we still need to make a few changes to get this project approved:muscle:.**

**To improve**
As highlighted by the last reviewer:

- [ ] Add rspec tests to the project. Both unit and integration tests that cover positive and negative case scenarios.

- [ ] After logging, the root page of the project should only show posts from the current user and its friends. Currently, It shows posts from all users registered on the app. Kindly fix this.

- [x] Current user should be able to make friendship requests. Also fix this.

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 

Hello team @abmAsadullah 👋🏾 👋🏾 , great job on working on this milestone 😄 

#### Highlights

- You have used the correct git-flow ✔️ 
- A user is able to send and receive requests ✔️ 
- Linter checks are not giving any errors ✔️ 

#### To improve

- [x] As a logged-in user, I should only see my posts and posts from my friends, currently, I see posts from all users in the app. 
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x]  Add RSpec tests to the project. Both unit and integration tests cover positive and negative case scenarios. Currently, you only have one test in your project. Add more tests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
_If you have any questions, kindly leave a comment here and tag my name @mimipeshy and I will be glad to help_

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
## **Changes Required 🛑♻**

<hr>

Hello there 😊
Great job working on the requested changes. You've done the timeline posts logic very well! However, it seems you still have some issues with the RSpec tests.

- [x] Please fix the issue that occurs while running the tests. Check the image below!
Git-Bksh__c_Users_mbakr_OneDrive_Desktop_social-media-app 5_6_2021 7_36_21 PM

<hr>

Good luck and happy coding 👨‍💻💻

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @abmAsadullah ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
